language: python
python:
- '3.6'
env:
- LD_LIBRARY_PATH=$HOME/.hapdab/lib:$LD_LIBRARY_PATH PATH=$HOME/.hapdab/bin:$HOME/.hapdab/conda/bin:$PATH
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n hapdab python=3 Cython numpy pandas pytest pytest-cov
- source activate hapdab
- python setup.py install
- pip install codecov
script:
- source activate hapdab
- cd tests
- py.test -v --cov=hapdab
- codecov
after_success:
- coveralls
deploy:
  provider: pypi
  user: schae234
  password:
    secure: UqcxM/nOh5x4gYkyD+tdE+i+UvqGujuP7nnk1AYJIi8jdcY+oQR6sOY3ci/T4gzXaHFDnfhKJRP3N5ZjQHWpQq/Z0SymdrC7PVgPV2MeRthnGuN3R1UFZ6FzvB3SQHoTx/Cr+LC+kUTvD/MxLHGk5YVlFw5jPuskEpRGV96zQmZcLfmU7qYMBQ5wHYn7tIU58KqsajVvoZDop+f0pHNwIMQnGd7mmVPGkDnBsGCB9foRTwt4qpVrtFRn/Jb5IrVFDOXIDXvXL2al6tFOyJHqNKMY5/mhOUVMI3eGaE7wucI+jybzXdzStABBZ0Pg0fhFz9jPD9xPQNS+GfB4Rh/QT6Bdu/CvK7yviH9T8B91sRWTs5LCNiJ1zoNGAqiahN1sIab00w/2Rqyaz31tTxVf5kb5FrDMLkhJvcYiAIcXgcCTa5dZ2LP8aAUneHE9cPxl1tqkz2o3rqjPFUgO5ijYhDwlmY69HwmofonrFc+Da1BruTSFdszY+rVE5o2ktx9GIHbpw/3MBftU3c5Kdo/4KAQC7V62+twKf5uco5f7U5JO5RYx3wyqJ00/YW68CATC4as56ipGO1n2JusgG0sKYKqJ+hGWDqEaTD5ejB2C5BJ02QtVEGOO1f3wXrxVKow7kvydw3QunPP1VdAH2SLfaPY79Q6gnM/93TgAcfw7TDc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: LinkageIO/HapDab
